;*************************************************
;*****   System
;*************************************************
daemon off  
log_level 6
log_type ALL
;log_file   

;*************************************************
;*****   Camera
;*************************************************
;device_name 
;device_id   
;target_dir  

;*************************************************
;*****   Source
;*************************************************
;v4l2_device /dev/video0
;netcam_url rtsp://username:password@192.168.1.100:554/stream1

;*************************************************
;*****   Image
;*************************************************
;width 640   
;height 480   
;framerate 15 

;*************************************************
;*****   Overlays
;*************************************************
text_right %Y-%m-%d\n%T

;*************************************************
;*****   Method
;*************************************************
emulate_motion off
threshold 1500  

;*************************************************
;*****   Masks
;*************************************************
noise_level 32         
despeckle_filter EedDl

;*************************************************
;*****   Detection
;*************************************************
minimum_motion_frames 1 
event_gap 60           
pre_capture 3           
post_capture 10         

;*************************************************
;*****   Scripts
;*************************************************
on_event_start 
on_event_end  

;*************************************************
;*****   Picture
;*************************************************
picture_output off                  
picture_filename %v-%Y%m%d%H%M%S-%q 

;*************************************************
;*****   Movie
;*************************************************
movie_output on                
movie_max_time 120              
movie_quality 45               
movie_container mkv            
movie_filename %v-%Y%m%d%H%M%S  

;*************************************************
;*****   LoopBack
;*************************************************
video_pipe /dev/video1

;*************************************************
;*****   Web Control
;*************************************************
webcontrol_port 8081   
webcontrol_localhost on
webcontrol_parms 0     

;*************************************************
;*****   Web Stream
;*************************************************
stream_preview_scale 30
stream_preview_method static

device_tmo 10
watchdog_tmo 10

;*************************************************
;*****   Data Base
;*************************************************
database_type sqlite3
database_dbname /home/alex/Desktop/xuanshiNVR/bin/bin/bin/nvr.db
database_busy_timeout 3000

;*************************************************
; Device config files - One for each device.
;*************************************************
camera ./camera1-dist.conf