;*************************************************
; Configuration options specific to camera 1
;*************************************************

;*****   Camera
device_name MyCam1
device_id 101

;*****   Source
;v4l2_device /dev/video0
netcam_url rtsp://alex:123@127.0.0.1:8554/stream0

;*****   Image
width 1280
height 720

;*****   Overlays
text_left ZHENTONG DEMO

;*****   Movie
movie_filename CAM01_%t-%v-%Y%m%d%H%M%S


