/*
  Configuration parameter tables.
  Split out of conf.cpp: only the static config_parms /
  config_parms_depr tables.  NOTE: the ordering of config_parms is
  significant and is relied upon by the webui post handler.  Each
  table ends with a sentinel entry of empty strings.
*/
#include "core/ztnvr.hpp"
#include "platform/utils/util.hpp"
#include "platform/logger/logger.hpp"
#include "media/cam/camera.hpp"
#include "media/sound/sound.hpp"
#include "conf/conf.hpp"

/*Configuration parameters */
ctx_parm config_parms[] = {
    {"daemon", PARM_TYP_BOOL, PARM_CAT_00, PARM_LEVEL_ADVANCED},
    {"conf_filename", PARM_TYP_STRING, PARM_CAT_00, PARM_LEVEL_ADVANCED},
    {"pid_file", PARM_TYP_STRING, PARM_CAT_00, PARM_LEVEL_ADVANCED},
    {"log_file", PARM_TYP_STRING, PARM_CAT_00, PARM_LEVEL_ADVANCED},
    {"log_level", PARM_TYP_LIST, PARM_CAT_00, PARM_LEVEL_LIMITED},
    {"log_fflevel", PARM_TYP_LIST, PARM_CAT_00, PARM_LEVEL_LIMITED},
    {"log_type", PARM_TYP_LIST, PARM_CAT_00, PARM_LEVEL_LIMITED},
    {"native_language", PARM_TYP_BOOL, PARM_CAT_00, PARM_LEVEL_LIMITED},

    {"device_name", PARM_TYP_STRING, PARM_CAT_01, PARM_LEVEL_LIMITED},
    {"device_id", PARM_TYP_INT, PARM_CAT_01, PARM_LEVEL_LIMITED},
    {"device_tmo", PARM_TYP_INT, PARM_CAT_01, PARM_LEVEL_LIMITED},
    {"pause", PARM_TYP_LIST, PARM_CAT_01, PARM_LEVEL_LIMITED},
    {"schedule_params", PARM_TYP_STRING, PARM_CAT_01, PARM_LEVEL_LIMITED},
    {"cleandir_params", PARM_TYP_STRING, PARM_CAT_01, PARM_LEVEL_LIMITED},
    {"target_dir", PARM_TYP_STRING, PARM_CAT_01, PARM_LEVEL_ADVANCED},
    {"watchdog_tmo", PARM_TYP_INT, PARM_CAT_01, PARM_LEVEL_LIMITED},
    {"watchdog_kill", PARM_TYP_INT, PARM_CAT_01, PARM_LEVEL_LIMITED},
    {"config_dir", PARM_TYP_STRING, PARM_CAT_01, PARM_LEVEL_ADVANCED},
    {"camera", PARM_TYP_STRING, PARM_CAT_01, PARM_LEVEL_ADVANCED},

    {"v4l2_device", PARM_TYP_STRING, PARM_CAT_02, PARM_LEVEL_ADVANCED},
    {"v4l2_params", PARM_TYP_STRING, PARM_CAT_02, PARM_LEVEL_ADVANCED},
    {"netcam_url", PARM_TYP_STRING, PARM_CAT_02, PARM_LEVEL_ADVANCED},
    {"netcam_params", PARM_TYP_STRING, PARM_CAT_02, PARM_LEVEL_ADVANCED},
    {"netcam_high_url", PARM_TYP_STRING, PARM_CAT_02, PARM_LEVEL_ADVANCED},
    {"netcam_high_params", PARM_TYP_STRING, PARM_CAT_02, PARM_LEVEL_ADVANCED},
    {"netcam_userpass", PARM_TYP_STRING, PARM_CAT_02, PARM_LEVEL_ADVANCED},
    {"libcam_device", PARM_TYP_STRING, PARM_CAT_02, PARM_LEVEL_ADVANCED},
    {"libcam_params", PARM_TYP_STRING, PARM_CAT_02, PARM_LEVEL_ADVANCED},

    {"width", PARM_TYP_INT, PARM_CAT_03, PARM_LEVEL_LIMITED},
    {"height", PARM_TYP_INT, PARM_CAT_03, PARM_LEVEL_LIMITED},
    {"framerate", PARM_TYP_INT, PARM_CAT_03, PARM_LEVEL_LIMITED},
    {"rotate", PARM_TYP_LIST, PARM_CAT_03, PARM_LEVEL_LIMITED},
    {"flip_axis", PARM_TYP_LIST, PARM_CAT_03, PARM_LEVEL_LIMITED},

    {"locate_motion_mode", PARM_TYP_LIST, PARM_CAT_04, PARM_LEVEL_LIMITED},
    {"locate_motion_style", PARM_TYP_LIST, PARM_CAT_04, PARM_LEVEL_LIMITED},
    {"text_left", PARM_TYP_STRING, PARM_CAT_04, PARM_LEVEL_LIMITED},
    {"text_right", PARM_TYP_STRING, PARM_CAT_04, PARM_LEVEL_LIMITED},
    {"text_changes", PARM_TYP_BOOL, PARM_CAT_04, PARM_LEVEL_LIMITED},
    {"text_scale", PARM_TYP_LIST, PARM_CAT_04, PARM_LEVEL_LIMITED},
    {"text_event", PARM_TYP_STRING, PARM_CAT_04, PARM_LEVEL_LIMITED},

    {"emulate_motion", PARM_TYP_BOOL, PARM_CAT_05, PARM_LEVEL_LIMITED},
    {"threshold", PARM_TYP_INT, PARM_CAT_05, PARM_LEVEL_LIMITED},
    {"threshold_maximum", PARM_TYP_INT, PARM_CAT_05, PARM_LEVEL_LIMITED},
    {"threshold_sdevx", PARM_TYP_INT, PARM_CAT_05, PARM_LEVEL_LIMITED},
    {"threshold_sdevy", PARM_TYP_INT, PARM_CAT_05, PARM_LEVEL_LIMITED},
    {"threshold_sdevxy", PARM_TYP_INT, PARM_CAT_05, PARM_LEVEL_LIMITED},
    {"threshold_ratio", PARM_TYP_INT, PARM_CAT_05, PARM_LEVEL_LIMITED},
    {"threshold_ratio_change", PARM_TYP_INT, PARM_CAT_05, PARM_LEVEL_LIMITED},
    {"threshold_tune", PARM_TYP_BOOL, PARM_CAT_05, PARM_LEVEL_LIMITED},
    {"secondary_method", PARM_TYP_LIST, PARM_CAT_05, PARM_LEVEL_LIMITED},
    {"secondary_params", PARM_TYP_STRING, PARM_CAT_05, PARM_LEVEL_LIMITED},

    {"noise_level", PARM_TYP_INT, PARM_CAT_06, PARM_LEVEL_LIMITED},
    {"noise_tune", PARM_TYP_BOOL, PARM_CAT_06, PARM_LEVEL_LIMITED},
    {"despeckle_filter", PARM_TYP_STRING, PARM_CAT_06, PARM_LEVEL_LIMITED},
    {"area_detect", PARM_TYP_STRING, PARM_CAT_06, PARM_LEVEL_LIMITED},
    {"mask_file", PARM_TYP_STRING, PARM_CAT_06, PARM_LEVEL_ADVANCED},
    {"mask_privacy", PARM_TYP_STRING, PARM_CAT_06, PARM_LEVEL_ADVANCED},
    {"smart_mask_speed", PARM_TYP_LIST, PARM_CAT_06, PARM_LEVEL_LIMITED},

    {"lightswitch_percent", PARM_TYP_INT, PARM_CAT_07, PARM_LEVEL_LIMITED},
    {"lightswitch_frames", PARM_TYP_INT, PARM_CAT_07, PARM_LEVEL_LIMITED},
    {"minimum_motion_frames", PARM_TYP_INT, PARM_CAT_07, PARM_LEVEL_LIMITED},
    {"static_object_time", PARM_TYP_INT, PARM_CAT_07, PARM_LEVEL_LIMITED},
    {"event_gap", PARM_TYP_INT, PARM_CAT_07, PARM_LEVEL_LIMITED},
    {"pre_capture", PARM_TYP_INT, PARM_CAT_07, PARM_LEVEL_LIMITED},
    {"post_capture", PARM_TYP_INT, PARM_CAT_07, PARM_LEVEL_LIMITED},

    {"on_event_start", PARM_TYP_STRING, PARM_CAT_08, PARM_LEVEL_RESTRICTED},
    {"on_event_end", PARM_TYP_STRING, PARM_CAT_08, PARM_LEVEL_RESTRICTED},
    {"on_picture_save", PARM_TYP_STRING, PARM_CAT_08, PARM_LEVEL_RESTRICTED},
    {"on_area_detected", PARM_TYP_STRING, PARM_CAT_08, PARM_LEVEL_RESTRICTED},
    {"on_motion_detected", PARM_TYP_STRING, PARM_CAT_08, PARM_LEVEL_RESTRICTED},
    {"on_movie_start", PARM_TYP_STRING, PARM_CAT_08, PARM_LEVEL_RESTRICTED},
    {"on_movie_end", PARM_TYP_STRING, PARM_CAT_08, PARM_LEVEL_RESTRICTED},
    {"on_camera_lost", PARM_TYP_STRING, PARM_CAT_08, PARM_LEVEL_RESTRICTED},
    {"on_camera_found", PARM_TYP_STRING, PARM_CAT_08, PARM_LEVEL_RESTRICTED},
    {"on_secondary_detect", PARM_TYP_STRING, PARM_CAT_08,
     PARM_LEVEL_RESTRICTED},
    {"on_action_user", PARM_TYP_STRING, PARM_CAT_08, PARM_LEVEL_RESTRICTED},
    {"on_sound_alert", PARM_TYP_STRING, PARM_CAT_08, PARM_LEVEL_RESTRICTED},

    {"picture_output", PARM_TYP_LIST, PARM_CAT_09, PARM_LEVEL_LIMITED},
    {"picture_output_motion", PARM_TYP_LIST, PARM_CAT_09, PARM_LEVEL_LIMITED},
    {"picture_type", PARM_TYP_LIST, PARM_CAT_09, PARM_LEVEL_LIMITED},
    {"picture_quality", PARM_TYP_INT, PARM_CAT_09, PARM_LEVEL_LIMITED},
    {"picture_exif", PARM_TYP_STRING, PARM_CAT_09, PARM_LEVEL_LIMITED},
    {"picture_filename", PARM_TYP_STRING, PARM_CAT_09, PARM_LEVEL_LIMITED},
    {"snapshot_interval", PARM_TYP_INT, PARM_CAT_09, PARM_LEVEL_LIMITED},
    {"snapshot_filename", PARM_TYP_STRING, PARM_CAT_09, PARM_LEVEL_LIMITED},

    {"movie_output", PARM_TYP_BOOL, PARM_CAT_10, PARM_LEVEL_LIMITED},
    {"movie_output_motion", PARM_TYP_BOOL, PARM_CAT_10, PARM_LEVEL_LIMITED},
    {"movie_max_time", PARM_TYP_INT, PARM_CAT_10, PARM_LEVEL_LIMITED},
    {"movie_bps", PARM_TYP_INT, PARM_CAT_10, PARM_LEVEL_LIMITED},
    {"movie_quality", PARM_TYP_INT, PARM_CAT_10, PARM_LEVEL_LIMITED},
    {"movie_container", PARM_TYP_STRING, PARM_CAT_10, PARM_LEVEL_LIMITED},
    {"movie_passthrough", PARM_TYP_BOOL, PARM_CAT_10, PARM_LEVEL_LIMITED},
    {"movie_filename", PARM_TYP_STRING, PARM_CAT_10, PARM_LEVEL_LIMITED},
    {"movie_retain", PARM_TYP_LIST, PARM_CAT_10, PARM_LEVEL_LIMITED},
    {"movie_extpipe_use", PARM_TYP_BOOL, PARM_CAT_10, PARM_LEVEL_RESTRICTED},
    {"movie_extpipe", PARM_TYP_STRING, PARM_CAT_10, PARM_LEVEL_RESTRICTED},

    {"timelapse_interval", PARM_TYP_INT, PARM_CAT_11, PARM_LEVEL_LIMITED},
    {"timelapse_mode", PARM_TYP_LIST, PARM_CAT_11, PARM_LEVEL_LIMITED},
    {"timelapse_fps", PARM_TYP_INT, PARM_CAT_11, PARM_LEVEL_LIMITED},
    {"timelapse_container", PARM_TYP_LIST, PARM_CAT_11, PARM_LEVEL_LIMITED},
    {"timelapse_filename", PARM_TYP_STRING, PARM_CAT_11, PARM_LEVEL_LIMITED},

    {"video_pipe", PARM_TYP_STRING, PARM_CAT_12, PARM_LEVEL_LIMITED},
    {"video_pipe_motion", PARM_TYP_STRING, PARM_CAT_12, PARM_LEVEL_LIMITED},

    {"webcontrol_port", PARM_TYP_INT, PARM_CAT_13, PARM_LEVEL_ADVANCED},
    {"webcontrol_port2", PARM_TYP_INT, PARM_CAT_13, PARM_LEVEL_ADVANCED},
    {"webcontrol_base_path", PARM_TYP_STRING, PARM_CAT_13, PARM_LEVEL_ADVANCED},
    {"webcontrol_ipv6", PARM_TYP_BOOL, PARM_CAT_13, PARM_LEVEL_ADVANCED},
    {"webcontrol_localhost", PARM_TYP_BOOL, PARM_CAT_13, PARM_LEVEL_ADVANCED},
    {"webcontrol_parms", PARM_TYP_LIST, PARM_CAT_13, PARM_LEVEL_NEVER},
    {"webcontrol_interface", PARM_TYP_LIST, PARM_CAT_13, PARM_LEVEL_ADVANCED},
    {"webcontrol_auth_method", PARM_TYP_LIST, PARM_CAT_13,
     PARM_LEVEL_RESTRICTED},
    {"webcontrol_authentication", PARM_TYP_STRING, PARM_CAT_13,
     PARM_LEVEL_RESTRICTED},
    {"webcontrol_tls", PARM_TYP_BOOL, PARM_CAT_13, PARM_LEVEL_RESTRICTED},
    {"webcontrol_cert", PARM_TYP_STRING, PARM_CAT_13, PARM_LEVEL_RESTRICTED},
    {"webcontrol_key", PARM_TYP_STRING, PARM_CAT_13, PARM_LEVEL_RESTRICTED},
    {"webcontrol_headers", PARM_TYP_STRING, PARM_CAT_13, PARM_LEVEL_ADVANCED},
    {"webcontrol_html", PARM_TYP_STRING, PARM_CAT_13, PARM_LEVEL_ADVANCED},
    {"webcontrol_actions", PARM_TYP_STRING, PARM_CAT_13, PARM_LEVEL_RESTRICTED},
    {"webcontrol_lock_minutes", PARM_TYP_INT, PARM_CAT_13, PARM_LEVEL_ADVANCED},
    {"webcontrol_lock_attempts", PARM_TYP_INT, PARM_CAT_13,
     PARM_LEVEL_ADVANCED},
    {"webcontrol_lock_script", PARM_TYP_STRING, PARM_CAT_13,
     PARM_LEVEL_RESTRICTED},

    {"stream_preview_scale", PARM_TYP_INT, PARM_CAT_14, PARM_LEVEL_LIMITED},
    {"stream_preview_newline", PARM_TYP_BOOL, PARM_CAT_14, PARM_LEVEL_LIMITED},
    {"stream_preview_params", PARM_TYP_STRING, PARM_CAT_14, PARM_LEVEL_LIMITED},
    {"stream_preview_method", PARM_TYP_LIST, PARM_CAT_14, PARM_LEVEL_LIMITED},
    {"stream_preview_ptz", PARM_TYP_BOOL, PARM_CAT_14, PARM_LEVEL_LIMITED},
    {"stream_quality", PARM_TYP_INT, PARM_CAT_14, PARM_LEVEL_LIMITED},
    {"stream_grey", PARM_TYP_BOOL, PARM_CAT_14, PARM_LEVEL_LIMITED},
    {"stream_motion", PARM_TYP_BOOL, PARM_CAT_14, PARM_LEVEL_LIMITED},
    {"stream_maxrate", PARM_TYP_INT, PARM_CAT_14, PARM_LEVEL_LIMITED},
    {"stream_scan_time", PARM_TYP_INT, PARM_CAT_14, PARM_LEVEL_LIMITED},
    {"stream_scan_scale", PARM_TYP_INT, PARM_CAT_14, PARM_LEVEL_LIMITED},

    {"database_type", PARM_TYP_LIST, PARM_CAT_15, PARM_LEVEL_ADVANCED},
    {"database_dbname", PARM_TYP_STRING, PARM_CAT_15, PARM_LEVEL_ADVANCED},
    {"database_host", PARM_TYP_STRING, PARM_CAT_15, PARM_LEVEL_ADVANCED},
    {"database_port", PARM_TYP_INT, PARM_CAT_15, PARM_LEVEL_ADVANCED},
    {"database_user", PARM_TYP_STRING, PARM_CAT_15, PARM_LEVEL_RESTRICTED},
    {"database_password", PARM_TYP_STRING, PARM_CAT_15, PARM_LEVEL_RESTRICTED},
    {"database_busy_timeout", PARM_TYP_INT, PARM_CAT_15, PARM_LEVEL_ADVANCED},

    {"sql_event_start", PARM_TYP_STRING, PARM_CAT_16, PARM_LEVEL_ADVANCED},
    {"sql_event_end", PARM_TYP_STRING, PARM_CAT_16, PARM_LEVEL_ADVANCED},
    {"sql_movie_start", PARM_TYP_STRING, PARM_CAT_16, PARM_LEVEL_ADVANCED},
    {"sql_movie_end", PARM_TYP_STRING, PARM_CAT_16, PARM_LEVEL_ADVANCED},
    {"sql_pic_save", PARM_TYP_STRING, PARM_CAT_16, PARM_LEVEL_ADVANCED},

    {"ptz_auto_track", PARM_TYP_BOOL, PARM_CAT_17, PARM_LEVEL_LIMITED},
    {"ptz_wait", PARM_TYP_INT, PARM_CAT_17, PARM_LEVEL_LIMITED},
    {"ptz_move_track", PARM_TYP_STRING, PARM_CAT_17, PARM_LEVEL_RESTRICTED},
    {"ptz_pan_left", PARM_TYP_STRING, PARM_CAT_17, PARM_LEVEL_RESTRICTED},
    {"ptz_pan_right", PARM_TYP_STRING, PARM_CAT_17, PARM_LEVEL_RESTRICTED},
    {"ptz_tilt_up", PARM_TYP_STRING, PARM_CAT_17, PARM_LEVEL_RESTRICTED},
    {"ptz_tilt_down", PARM_TYP_STRING, PARM_CAT_17, PARM_LEVEL_RESTRICTED},
    {"ptz_zoom_in", PARM_TYP_STRING, PARM_CAT_17, PARM_LEVEL_RESTRICTED},
    {"ptz_zoom_out", PARM_TYP_STRING, PARM_CAT_17, PARM_LEVEL_RESTRICTED},

    {"snd_device", PARM_TYP_STRING, PARM_CAT_18, PARM_LEVEL_ADVANCED},
    {"snd_params", PARM_TYP_STRING, PARM_CAT_18, PARM_LEVEL_ADVANCED},
    {"snd_alerts", PARM_TYP_ARRAY, PARM_CAT_18, PARM_LEVEL_ADVANCED},
    {"snd_window", PARM_TYP_LIST, PARM_CAT_18, PARM_LEVEL_ADVANCED},
    {"snd_show", PARM_TYP_BOOL, PARM_CAT_18, PARM_LEVEL_ADVANCED},

    {"", (enum PARM_TYP)0, (enum PARM_CAT)0, (enum PARM_LEVEL)0}};

/*
 * Array of deprecated config options:
 * When deprecating an option, remove it from above (config_parms array)
 * and create an entry in this array of name, last version, info,
 * and (if applicable) a replacement conf value and copy funcion.
 * Upon reading a deprecated config option, a warning will be logged
 * with the given information and last version it was used in.
 * If set, the given value will be copied into the conf value
 * for backwards compatibility.
 */

/* Array of deprecated config options */
ctx_parm_depr config_parms_depr[] = {
    {"thread", "3.4.1",
     "The \"thread\" option has been replaced by the \"camera\"", "camera"},
    {"ffmpeg_timelapse", "4.0.1",
     "\"ffmpeg_timelapse\" replaced with \"timelapse_interval\"",
     "timelapse_interval"},
    {"ffmpeg_timelapse_mode", "4.0.1",
     "\"ffmpeg_timelapse_mode\" replaced with \"timelapse_mode\"",
     "timelapse_mode"},
    {"brightness", "4.1.1", "\"brightness\" replaced with \"v4l2_params\"",
     "v4l2_params"},
    {"contrast", "4.1.1", "\"contrast\" replaced with \"v4l2_params\"",
     "v4l2_params"},
    {"saturation", "4.1.1", "\"saturation\" replaced with \"v4l2_params\"",
     "v4l2_params"},
    {"hue", "4.1.1", "\"hue\" replaced with \"v4l2_params\"", "v4l2_params"},
    {"power_line_frequency", "4.1.1",
     "\"power_line_frequency\" replaced with \"v4l2_params\"", "v4l2_params"},
    {"text_double", "4.1.1", "\"text_double\" replaced with \"text_scale\"",
     "text_scale"},
    {"webcontrol_html_output", "4.1.1",
     "\"webcontrol_html_output\" replaced with \"webcontrol_interface\"",
     "webcontrol_interface"},
    {"lightswitch", "4.1.1",
     "\"lightswitch\" replaced with \"lightswitch_percent\"",
     "lightswitch_percent"},
    {"ffmpeg_output_movies", "4.1.1",
     "\"ffmpeg_output_movies\" replaced with \"movie_output\"", "movie_output"},
    {"ffmpeg_output_debug_movies", "4.1.1",
     "\"ffmpeg_output_debug_movies\" replaced with \"movie_output_motion\"",
     "movie_output_motion"},
    {"max_movie_time", "4.1.1",
     "\"max_movie_time\" replaced with \"movie_max_time\"", "movie_max_time"},
    {"ffmpeg_bps", "4.1.1", "\"ffmpeg_bps\" replaced with \"movie_bps\"",
     "movie_bps"},
    {"ffmpeg_variable_bitrate", "4.1.1",
     "\"ffmpeg_variable_bitrate\" replaced with \"movie_quality\"",
     "movie_quality"},
    {"ffmpeg_video_codec", "4.1.1",
     "\"ffmpeg_video_codec\" replaced with \"movie_container\"",
     "movie_container"},
    {"ffmpeg_passthrough", "4.1.1",
     "\"ffmpeg_passthrough\" replaced with \"movie_passthrough\"",
     "movie_passthrough"},
    {"use_extpipe", "4.1.1",
     "\"use_extpipe\" replaced with \"movie_extpipe_use\"",
     "movie_extpipe_use"},
    {"extpipe", "4.1.1", "\"extpipe\" replaced with \"movie_extpipe\"",
     "movie_extpipe"},
    {"output_pictures", "4.1.1",
     "\"output_pictures\" replaced with \"picture_output\"", "picture_output"},
    {"output_debug_pictures", "4.1.1",
     "\"output_debug_pictures\" replaced with \"picture_output_motion\"",
     "picture_output_motion"},
    {"quality", "4.1.1", "\"quality\" replaced with \"picture_quality\"",
     "picture_quality"},
    {"exif_text", "4.1.1", "\"exif_text\" replaced with \"picture_exif\"",
     "picture_exif"},
    {"motion_video_pipe", "4.1.1",
     "\"motion_video_pipe\" replaced with \"video_pipe_motion\"",
     "video_pipe_motion"},
    {"ipv6_enabled", "4.1.1",
     "\"ipv6_enabled\" replaced with \"webcontrol_ipv6\"", "webcontrol_ipv6"},
    {"rtsp_uses_tcp", "4.1.1",
     "\"rtsp_uses_tcp\" replaced with \"netcam_use_tcp\"", "netcam_use_tcp"},
    {"switchfilter", "4.1.1",
     "\"switchfilter\" replaced with \"roundrobin_switchfilter\"",
     "roundrobin_switchfilter"},
    {"logfile", "4.1.1", "\"logfile\" replaced with \"log_file\"", "log_file"},
    {"process_id_file", "4.1.1",
     "\"process_id_file\" replaced with \"pid_file\"", "pid_file"},
    {"movie_codec", "0.0.1",
     "\"movie_codec\" replaced with \"movie_container\"", "movie_container"},
    {"camera_id", "0.0.1", "\"camera_id\" replaced with \"device_id\"",
     "device_id"},
    {"camera_name", "0.0.1", "\"camera_name\" replaced with \"device_name\"",
     "device_name"},
    {"camera_tmo", "0.0.1", "\"camera_tmo\" replaced with \"device_tmo\"",
     "device_tmo"},
    {"libcam_name", "0.0.1", "\"libcam_name\" replaced with \"libcam_device\"",
     "libcam_device"},
    {"", "", "", ""}};
